name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_cube: ^0.1.1
  flutter_gl: ^0.0.21
  vector_math: ^2.2.0
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_ai: ^3.3.0
  flutter_riverpod: ^3.0.1
  provider: ^6.1.5+1
  web_socket_channel: ^3.0.3
  http: ^1.5.0
  shimmer: ^3.0.0
  crypto_font_icons: ^1.0.1
  animated_text_kit: ^4.3.0
  fl_chart: ^1.1.1
  geolocator: ^14.0.2
  glass_kit: ^4.0.2
  geocoding: ^4.0.0
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/14275263.png

# --- APP ICON CONFIGURATION ---
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/14275263.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  image_path: "assets/14275263.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/14275263.png"
  min_sdk_android: 21

# --- SPLASH SCREEN CONFIGURATION ---
flutter_native_splash:
  color: "#ffffff"
  image: assets/14275263.png
  android_12:
    image: assets/14275263.png
    icon_background_color: "#ffffff"
  web: true